"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const type_graphql_1 = require("../../prisma/generated/type-graphql");
const User_1 = require("../resolvers/User");
const AnswerMessage_1 = require("../resolvers/AnswerMessage");
const Auth_1 = require("../resolvers/Auth");
const Project_1 = require("./Project");
const Message_1 = require("../resolvers/Message");
const messageSubResolver_1 = require("../resolvers/subscriptions/messageSubResolver");
exports.default = [
    Message_1.MessageResolver,
    AnswerMessage_1.AnswerMessageResolver,
    messageSubResolver_1.MessageSubResolver,
    type_graphql_1.CreateStackResolver,
    type_graphql_1.FindManyStackResolver,
    type_graphql_1.UpdateStackResolver,
    type_graphql_1.DeleteStackResolver,
    Project_1.CreateProjectWithNestedRelationsResolver,
    type_graphql_1.TechCategoryRelationsResolver,
    type_graphql_1.AboutRelationsResolver,
    type_graphql_1.ProjectRelationsResolver,
    type_graphql_1.TechRelationsResolver,
    type_graphql_1.MessageRelationsResolver,
    type_graphql_1.SketchRelationsResolver,
    type_graphql_1.QuestionRelationsResolver,
    type_graphql_1.DeleteTechResolver,
    type_graphql_1.DeleteAboutResolver,
    type_graphql_1.CreateAboutResolver,
    type_graphql_1.DeleteProjectResolver,
    type_graphql_1.FindManyAboutResolver,
    type_graphql_1.DeleteQuestionResolver,
    type_graphql_1.UpdateAboutResolver,
    type_graphql_1.FindUniqueAboutResolver,
    type_graphql_1.DeleteTechCategoryResolver,
    type_graphql_1.DeleteManyAboutResolver,
    type_graphql_1.DeleteSketchResolver,
    type_graphql_1.CreateTechResolver,
    type_graphql_1.DeleteMessageResolver,
    type_graphql_1.CreateProjectResolver,
    type_graphql_1.CreateQuestionResolver,
    type_graphql_1.CreateTechCategoryResolver,
    type_graphql_1.CreateSketchResolver,
    type_graphql_1.FindManyTechResolver,
    type_graphql_1.FindManyProjectResolver,
    type_graphql_1.FindManyQuestionResolver,
    type_graphql_1.FindManyTechCategoryResolver,
    type_graphql_1.FindManySketchResolver,
    type_graphql_1.FindManyMessageResolver,
    type_graphql_1.UpdateTechResolver,
    type_graphql_1.UpdateProjectResolver,
    type_graphql_1.UpdateQuestionResolver,
    type_graphql_1.UpdateTechCategoryResolver,
    type_graphql_1.UpdateSketchResolver,
    type_graphql_1.UpdateMessageResolver,
    type_graphql_1.FindUniqueTechResolver,
    type_graphql_1.FindUniqueProjectResolver,
    type_graphql_1.FindUniqueQuestionResolver,
    type_graphql_1.FindUniqueTechCategoryResolver,
    type_graphql_1.FindUniqueSketchResolver,
    type_graphql_1.FindUniqueMessageResolver,
    type_graphql_1.DeleteManyTechResolver,
    type_graphql_1.DeleteManyProjectResolver,
    type_graphql_1.DeleteManyQuestionResolver,
    type_graphql_1.DeleteManyTechCategoryResolver,
    type_graphql_1.DeleteManySketchResolver,
    type_graphql_1.DeleteManyMessageResolver,
    Auth_1.AuthResolver,
    User_1.AdminCrudResolver,
    type_graphql_1.CreateManySketchResolver,
    type_graphql_1.CreateManyTechCategoryResolver,
    type_graphql_1.CreateManyQuestionResolver,
    type_graphql_1.CreateManyTechResolver,
];
//# sourceMappingURL=allResolvers.js.map